spring:
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
        default_batch_fetch_size: 100

decorator:
  datasource:
    p6spy:
      enable-logging: true



custom:
  site:
    baseUrl: http://localhost