spring:
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:

        use_sql_comments: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

custom:
  site:
    baseUrl: http://localhost